language: objective-c
osx_image: xcode9.0
xcode_project: Monads.xcodeproj
xcode_scheme: Monads
xcode_sdk: macosx10.13

script:
  - xcodebuild clean build test -project "Monads.xcodeproj" -scheme "Monads" -destination 'generic/platform=OS X'

after_success:
  - bash <(curl -s https://codecov.io/bash)
