language: objective-c
osx_image: xcode8.3
xcode_project: Monads.xcodeproj
xcode_scheme: Monads
xcode_sdk: macosx10.12

script:
- xcodebuild clean build test -project "Monads.xcodeproj" -scheme "Monads" -destination 'generic/platform=macOS'

after_success:
  - bash <(curl -s https://codecov.io/bash)
